### ISSUE TITLE
ERROR:root:Index 1 not in list at hugo_config apply_map

### ISSUE THREAD

**Issue by smoreface** [danielfdickinson/wpxr-to-static#2]
When running this script as described, I encounter this error (with traceback)

```
ERROR:root:Index 1 not in list at hugo_config apply_map: contains apply_modifiers for item in result apply modifiers: apply(modifier): pull-single once
Traceback (most recent call last):
  File "/Users/user/Development/wpxr-to-static/wpxr-to-static.py", line 1858, in <module>
    main()
  File "/Users/user/Development/wpxr-to-static/wpxr-to-static.py", line 1832, in main
    hugo_converter.convert_hugo_items()
  File "/Users/user/Development/wpxr-to-static/wpxr-to-static.py", line 1183, in convert_hugo_items
    self.tree_converter.find_list_apply_data_model(
  File "/Users/user/Development/wpxr-to-static/wpxr-to-static.py", line 857, in find_list_apply_data_model
    self.apply_data_model_to_list(
  File "/Users/user/Development/wpxr-to-static/wpxr-to-static.py", line 745, in apply_data_model_to_list
    result = self.apply_data_model_to_element(
  File "/Users/user/Development/wpxr-to-static/wpxr-to-static.py", line 698, in apply_data_model_to_element
    self.apply_contains_to_element_for_result_tree(
  File "/Users/user/Development/wpxr-to-static/wpxr-to-static.py", line 654, in apply_contains_to_element_for_result_tree
    result = self.apply_contains_map_to_element(
  File "/Users/user/Development/wpxr-to-static/wpxr-to-static.py", line 587, in apply_contains_map_to_element
    result = self.apply_modifiers_to_result(
  File "/Users/user/Development/wpxr-to-static/wpxr-to-static.py", line 511, in apply_modifiers_to_result
    result = self.apply_modifiers_to_item(
  File "/Users/user/Development/wpxr-to-static/wpxr-to-static.py", line 462, in apply_modifiers_to_item
    result = self.apply_modifier_map_to_item(
  File "/Users/user/Development/wpxr-to-static/wpxr-to-static.py", line 442, in apply_modifier_map_to_item
    result = self.apply_one_modifier_to_item(
  File "/Users/user/Development/wpxr-to-static/wpxr-to-static.py", line 412, in apply_one_modifier_to_item
    result = modifier_function(
```

I have no idea what it means, but the web implied that it has something to do with perhaps a module name and a function name interacting oddly?

environment:
Mac with M1 chip
venv for cleanliness
python 3.8 (since html5lib doesn't seem to support python 3.10)

**Comment by danielfdickinson** [comment]
I'll try to make some time to look into this and your other issue report, in the next few days (currently working on some other Hugo-related things). I'll also see if python3.10 is on html5lib's roadmap, or if I will have find a replacement at some point.

Thank you for trying this out!

And please let me know if you are able to convince your Mac to use the version of Python you intend, and the results, if you are able to do so.
